# Render.com deployment configuration (optional)
services:
  - type: web
    name: rpc-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
